<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SeaS_Uninstall</AssemblyName>
    <RootNamespace>SeaS.Uninstaller</RootNamespace>
    <Product>SeaS 卸载程序</Product>
    <AssemblyTitle>SeaS 卸载程序</AssemblyTitle>
    <ApplicationIcon>..\SeaS.App\Assets\seas.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

</Project>
